# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e28d9ba948ffda64d98ae387b3cb43b1955b01220f28665405c0ab9f4c8309b3a18a5ae6295fe80bac5e5ef86d98ed0ed7326bc4c9b28a64e787761a71895a7

test:
  secret_key_base: 756f6e0d121b69715570e3117bc3b650e228c5db2136f785cb3416d6678fb1cd05506f746f9cf8af2fcd6026abe65e751fb2367c62c6cf68114c67b4876f1bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
